* Models of Computation

*Early Works*
---------

* Recursive Function Theory
Recursive function theory is a model of computability that emerged from the work in number theory.

Earliest instance of recursive functions can be found in antiquity, though some of the most recent recorded treatments is found in the work of Grassmann and Peirce in defining addition and multiplication. A canonical work that makes use of recursive function is Dedekind’s Was sind und was sollen die Zahlen (1888). Peano builds upon this work for creating a logical foundation of mathematics which would then be used by Russell and Whitehead in their Principia Mathematica (1910—1913).

Skolem’s paper Begründung Der Elementaren Arithmetik Durch Die Rekurrierende Denkweise Ohne Anwendung Scheinbarer Veranderlichen Mit Unendlichem Ausdehnungsbereich (The foundations of elementary arithmetic established by the recursive mode of thought, without the use of apparent variables ranging over infinite domains) (1923) is also considered a fundamental advancement in making this mode of thinking first class.

** Main Works
*** Was sind und was sollen die Zahlen (1888)
*** Begründung Der Elementaren Arithmetik Durch Die Rekurrierende Denkweise Ohne Anwendung Scheinbarer Veranderlichen Mit Unendlichem Ausdehnungsbereich (1923)
*** Les Bases de la Logique Hilbertienne – Jacques Herbrand (1930)
*** Sur La Non-Contradiction de l’Arithmétique – Jacques Herbrand (1932)
*** Über formal unentscheidbare Sätze der Principia Mathematica und verwandter Systeme, I — Kurt Gödel (1931)
*** Rekursive Funktionen Paper – Rózsa Péter (1932)
*** Rekursive Funktionen Book – Rózsa Péter (1951)
*** Logic-Kalkül (Lectures on Logic) – David Hilbert (1920)
*** Neubegründung der Mathematik. Erste Mitteilung (The new grounding of mathematics: First report) – David Hilbert (1922)
*** Die logischen Grundlagen der Mathematik (The logical foundations of mathematics) – David Hilbert (1923)
*** Über das Unendliche (On the infinite) — David Hilbert (1926)
*** Grundzüge der theoretischen Logik – David Hilbert and Wilhelm Ackermann (1928)
*** Grundlagen der Mathematik, Vol. I – David Hilbert and Paul Bernays (1934)
*** General Recursive Functions of Natural Numbers – Stephen Kleene (1936)
*** λ-Definability and Recursiveness – Stephen Kleene (1936)
*** Introduction to Metamathematics – Stephen Kleene (1952)

*** Kleene

** Jacquard Loom
** Kleene Algebra
** Boolean Algebra
** Cellular Automata
** Lambda Calculus
** Post Tag Machines
** Turing Machine
** Wang Tiles
** [[https://en.wikipedia.org/wiki/Wang_B-machine][Wang Machines]]
